---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-bff
  labels:
    app: driver-bff
spec:
  selector:
    matchLabels:
      app: driver-bff
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: driver-bff
    spec:
      containers:
        - name: driver-bffcnt
          image: 997641515580.dkr.ecr.me-south-1.amazonaws.com/buddyapp-dev:latest
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: buddy
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: driver-bff
