---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buddy-bff
  namespace: default-dev
  labels:
    app: buddy-bff
spec:
  selector:
    matchLabels:
      app: buddy-bff
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: buddy-bff
    spec:
      containers:
        - name: driver-bffcnt
          image: 997641515580.dkr.ecr.me-south-1.amazonaws.com/buddyapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: NODE_ENV
            - name: OTP_EXPIRE
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: OTP_EXPIRE
            - name: MAX_REDIS_RETRY
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: MAX_REDIS_RETRY
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: REDIS_PORT
            - name: REDIS_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: REDIS_PREFIX
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: buddy-bff
                  key: REDIS_PASSWORD
            - name: SMS_HOST
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: SMS_HOST
            - name: SMS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: buddy-bff
                  key: SMS_API_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: buddy-bff
                  key: JWT_SECRET
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: MONGO_URL
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: buddy-bff
                  key: MONGO_PASS
            - name: DRIVER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: buddy-bff
                  key: DRIVER_API_URL
            - name: BUDDY_BFF_KEY
              valueFrom:
                secretKeyRef:
                  name: buddy-bff
                  key: BUDDY_BFF_KEY
            - name: MGW_KEY
              valueFrom:
                secretKeyRef:
                  name: buddy-bff
                  key: MGW_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: buddy
  namespace: default-dev
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: buddy-bff
